/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "p1",
    name: "batman",
    brandName: "SHFiguarts",
    price: 4999,
    discount: 5,
    tag: "sale",
    img: ["images/bm1.jpg", "images/bm1.jpg"],
    description:
      "Based on Michael Keaton's take on the caped crusader in Tim Burton's Batman 1989 film which became a cult classic that revived the era of superhero movies. It also brought a much darker and cool Batman onscreen for the first time.",
    specification: {
      size: "7 inches",
      material: "ABS",
      age: "13+",
    },
    inStock: true,
    rating: 4.1,
    type: "styled-figurine",
    categoryName: "DC",
    inWishlist: true,
  },
  {
    _id: "p2",
    name: "joker",
    brandName: "SHFiguarts",
    price: 11999,
    discount: 20,
    freeDelivery: true,
    tag: "new",
    img: ["images/joker1.jpg", "images/joker2.jpg", "images/joker3.jpg"],
    description:
      "The IKEMAN lineup famously consists of re-designs of famous Japanese illustrator Ricken in the Japanese Ikemen (“handsome men”) style. Joining the Ikemen lineup is the clown prince of Gotham. From the trademark purple suit to his mischievous grin to the long staff and 'Laughing Fish' held in each hand, this statue perfectly showcases the insanity of Batman's Arch Enemy Joker",
    specification: {
      size: "6 inches",
      material: "PVC",
      age: "5+",
    },
    inStock: true,
    rating: 4.2,
    type: "styled-figurine",
    categoryName: "DC",
  },
  {
    _id: "p3",
    name: "iron man",
    brandName: "SHFiguarts",
    price: 5999,
    img: ["images/im1.jpg", "images/im2.jpg", "images/im3.jpg"],
    description:
      "One of the best figures in this innovative new series, the self-proclaimed Genius, Playboy, Billionaire, Philanthropist is covered in a shiny die-cast armor and each joint is carefully designed to recreate the articulation of a truly human body.",
    specification: {
      size: "8 inches",
      material: "ABS",
      age: "5+",
    },
    rating: 3,
    inStock: true,
    type: "styled-figurine",
    categoryName: "marvel",
  },
  {
    _id: "p4",
    name: "doctor strange",
    brandName: "SHFiguarts",
    price: 8999,
    discount: 10,
    tag: "sold out",
    img: ["images/ds1.jpg", "images/ds2.jpg"],
    specification: {
      size: "5 inches",
      material: "PVC",
      age: "13+",
    },
    freeDelivery: true,
    rating: 5,
    inStock: false,
    description:
      "S.H.Figuarts welcomes Doctor Strange, as he prepares for new adventures in the upcoming Marvel Studios film Doctor Strange in the Multiverse of Madness! This Marvel figure includes effect parts and a cape for recreating your favourite dramatic scenes, as well as a newly sculpted body and Tamashii digital coloured head.",
    type: "styled-figurine",
    categoryName: "marvel",
  },
  {
    _id: "p5",
    name: "batman",
    brandName: "funko",
    price: 2999,
    discount: 5,
    tag: "sale",
    img: ["images/bm1.jpg", "images/bm1.jpg"],
    description:
      "Based on Michael Keaton's take on the caped crusader in Tim Burton's Batman 1989 film which became a cult classic that revived the era of superhero movies. It also brought a much darker and cool Batman onscreen for the first time.",
    specification: {
      size: "7 inches",
      material: "ABS",
      age: "13+",
    },
    inStock: true,
    rating: 4.1,
    type: "styled-figurine",
    categoryName: "naruto",
    inWishlist: true,
  },
  {
    _id: "p6",
    name: "joker",
    brandName: "funko",
    price: 3999,
    discount: 20,
    freeDelivery: true,
    tag: "new",
    img: ["images/joker1.jpg", "images/joker2.jpg", "images/joker3.jpg"],
    description:
      "The IKEMAN lineup famously consists of re-designs of famous Japanese illustrator Ricken in the Japanese Ikemen (“handsome men”) style. Joining the Ikemen lineup is the clown prince of Gotham. From the trademark purple suit to his mischievous grin to the long staff and 'Laughing Fish' held in each hand, this statue perfectly showcases the insanity of Batman's Arch Enemy Joker",
    specification: {
      size: "6 inches",
      material: "PVC",
      age: "5+",
    },
    inStock: true,
    rating: 4.2,
    type: "styled-figurine",
    categoryName: "Demon slayer",
  },
  {
    _id: "p7",
    name: "iron man",
    brandName: "funko",
    price: 6999,
    img: ["images/im1.jpg", "images/im2.jpg", "images/im3.jpg"],
    description:
      "One of the best figures in this innovative new series, the self-proclaimed Genius, Playboy, Billionaire, Philanthropist is covered in a shiny die-cast armor and each joint is carefully designed to recreate the articulation of a truly human body.",
    specification: {
      size: "8 inches",
      material: "ABS",
      age: "5+",
    },
    rating: 3,
    inStock: true,
    type: "styled-figurine",
    categoryName: "one piece",
  },
  {
    _id: "p8",
    name: "doctor starnge",
    brandName: "funko",
    price: 7500,
    discount: 10,
    tag: "sold out",
    img: ["images/ds1.jpg", "images/ds2.jpg"],
    specification: {
      size: "5 inches",
      material: "PVC",
      age: "13+",
    },
    freeDelivery: true,
    rating: 5,
    inStock: false,
    description:
      "S.H.Figuarts welcomes Doctor Strange, as he prepares for new adventures in the upcoming Marvel Studios film Doctor Strange in the Multiverse of Madness! This Marvel figure includes effect parts and a cape for recreating your favourite dramatic scenes, as well as a newly sculpted body and Tamashii digital coloured head.",
    type: "styled-figurine",
    categoryName: "tokyo revengers",
  },
  {
    _id: "p9",
    name: "batman",
    brandName: "banpresto",
    price: 1000,
    discount: 5,
    tag: "sale",
    img: ["images/bm1.jpg", "images/bm1.jpg"],
    description:
      "Based on Michael Keaton's take on the caped crusader in Tim Burton's Batman 1989 film which became a cult classic that revived the era of superhero movies. It also brought a much darker and cool Batman onscreen for the first time.",
    specification: {
      size: "7 inches",
      material: "ABS",
      age: "13+",
    },
    inStock: true,
    rating: 4.1,
    type: "styled-figurine",
    categoryName: "my hero academia",
    inWishlist: true,
  },
  {
    _id: "p10",
    name: "joker",
    brandName: "banpresto",
    price: 2000,
    discount: 20,
    freeDelivery: true,
    tag: "new",
    img: ["images/joker1.jpg", "images/joker2.jpg", "images/joker3.jpg"],
    description:
      "The IKEMAN lineup famously consists of re-designs of famous Japanese illustrator Ricken in the Japanese Ikemen (“handsome men”) style. Joining the Ikemen lineup is the clown prince of Gotham. From the trademark purple suit to his mischievous grin to the long staff and 'Laughing Fish' held in each hand, this statue perfectly showcases the insanity of Batman's Arch Enemy Joker",
    specification: {
      size: "6 inches",
      material: "PVC",
      age: "5+",
    },
    inStock: true,
    rating: 4.2,
    type: "styled-figurine",
    categoryName: "jujutsu kaisen",
  },
  {
    _id: "p11",
    name: "iron man",
    brandName: "banpresto",
    price: 8000,
    img: ["images/im1.jpg", "images/im2.jpg", "images/im3.jpg"],
    description:
      "One of the best figures in this innovative new series, the self-proclaimed Genius, Playboy, Billionaire, Philanthropist is covered in a shiny die-cast armor and each joint is carefully designed to recreate the articulation of a truly human body.",
    specification: {
      size: "8 inches",
      material: "ABS",
      age: "5+",
    },
    rating: 3,
    inStock: true,
    type: "styled-figurine",
    categoryName: "naruto",
  },
  {
    _id: "p12",
    name: "doctor strange",
    brandName: "banpresto",
    price: 16999,
    discount: 10,
    tag: "sold out",
    img: ["images/ds1.jpg", "images/ds2.jpg"],
    specification: {
      size: "5 inches",
      material: "PVC",
      age: "13+",
    },
    freeDelivery: true,
    rating: 5,
    inStock: false,
    description:
      "S.H.Figuarts welcomes Doctor Strange, as he prepares for new adventures in the upcoming Marvel Studios film Doctor Strange in the Multiverse of Madness! This Marvel figure includes effect parts and a cape for recreating your favourite dramatic scenes, as well as a newly sculpted body and Tamashii digital coloured head.",
    type: "styled-figurine",
    categoryName: "jujutsu kaisen",
  },
];
