const filterActions = {
  FILTER_OUTOFSTOCK: "FILTER_OUTOFSTOCK",
  FILTER_ON_SALE: " FILTER_ON_SALE",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  SORT_BY_RATING: "SORT_BY_RATING",
  FILTER_BY_CATEGORIES: "FILTER_BY_CATEGORIES",
  FILTER_BY_BRANDS: "FILTER_BY_BRANDS",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  FILTER_SEARCH: "FILTER_SEARCH",
  CLEAR_FILTERS: "CLEAR FILTERS",
};

const productActions = {
  LOADING: "LOADING",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  ERROR: "ERROR",
};

export { filterActions, productActions };
