const filterActions = {
  FILTER_OUTOFSTOCK: "FILTER_OUTOFSTOCK",
  FILTER_ON_SALE: " FILTER_ON_SALE",
  SORT_OPTION: "SORT_OPTION",
  FILTER_BY_CATEGORIES: "FILTER_BY_CATEGORIES",
  FILTER_BY_BRANDS: "FILTER_BY_BRANDS",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  FILTER_SEARCH: "FILTER_SEARCH",
  CLEAR_FILTERS: "CLEAR_FILTERS",
};

const productActions = {
  LOADING: "LOADING",
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  ERROR: "ERROR",
  LOAD_SINGLE_PRODUCT: "LOAD_SINGLE_PRODUCT",
};

export { filterActions, productActions };
