export const wishlistConstants = {
  LOADING: "WISHLIST_LOADING",
  LOAD_WISHLIST: "LOAD_WISHLIST",
  ERROR: "ERROR",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: " REMOVE_FROM_WISHLIST",
};

export const cartConstants = {
  LOADING: "CART_LOADING",
  LOAD_CART: "LOAD_CART",
  ERROR: "ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: " REMOVE_FROM_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
};


export const addressConstants = {
  LOADING: "ADDRESS_LOADING",
  LOAD_ADDRESSES: "LOAD_ADDRESSES",
  ERROR: "ERROR",
  ADD_ADDRESS: "ADD_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  REMOVE_ADDRESS: "REMOVE_ADDRESS",
};
