export const userAuthActions = {
  LOADING: "LOADING",
  LOAD_PRODUCTS: "LOAD_USER",
  ERROR: "ERROR",
  LOAD_USER_PROFILE: "LOAD_USER_PROFILE",
  LOGOUT: "LOGOUT",
  OPEN_AUTH_MODAL: "OPEN_AUTH_MODAL",
  CLOSE_AUTH_MODAL: "CLOSE_AUTH_MODAL",
};
